### ISSUE TITLE
`enumerate_device_extension_properties` doesn't seem to properly take care of the returned strings

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#12]
Calling the method returns `ExtensionProperties` with bogus data after their names, e.g.:

```
Vulkan.ExtensionProperties("VK_EXT_full_screen_exclusive\xf0\xef\x19@\x01\x16\xf2\x19@\x01P\xee\x19@\x04\x903\xb5\x0f\x01\xb2\x1e\x01\x02\x01\x06\x02H\e\xa4?\xe0\xee\x19@", v"0.0.4")
```

Seems like some null termination or length check is going wrong?

**Comment by Seelengrab** [comment]
May be an issue in `src/prewrap/conversions.jl:42`:

```
from_vk(T::Type{S}, str::NTuple{N,UInt8}) where {N,S <: AbstractString} = T(filter!(x -> x ≠ 0, UInt8[str...]))
```

Not 100% sure this method is hit during conversion, but if `str` comes from Vulkan (and it's NULL-terminated), shouldn't we drop everything after the first null byte and be done with it?

**Comment by serenity4** [comment]
For `ExtensionProperties` at least, the string is not NULL-terminated, rather it's a fixed array of characters. I guess however that some strings were defined as if they were NULL-terminated strings, though I can't reproduce the bug on my side. In any case I agree that we should just stop after the first NULL character is read. I'll make the fix.

**Comment by serenity4** [comment]
I just saw that the char you got right after the end was `\xf0`, and not `\0` as would be the case for a NULL character. Or maybe it's a OS difference? I'm on Arch Linux. Please feel free to check that the issue is actually resolved for you and re-open it if necessary.

**Comment by Seelengrab** [comment]
According to [this](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkEnumerateDeviceExtensionProperties.html), `pLayerName` is either `NULL` or a null-terminated UTF-8 String, that's why I was thinking along that route.

**Comment by Seelengrab** [comment]
According to [this](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkExtensionProperties.html), while there is a maximum size, it's also a null-terminated UTF-8 string. I suppose the maximum size is there for performance reasons, to allow it to be stored inline while still being null-terminated conventionally. 

> extensionName is an array of VK_MAX_EXTENSION_NAME_SIZE char containing a null-terminated UTF-8 string which is the name of the extension.

The character I got was `\xf0` probably because the original code filtered out the null byte :)

**Comment by serenity4** [comment]
I see, it's great to have it fixed then, thanks for reporting this bug :100:

**Comment by Seelengrab** [comment]
You're welcome! We'll see what else I'll stumble upon while working through vulkan-tutorial.com :D The code is surprisingly 1:1 so far, I'm amazed!

**Comment by serenity4** [comment]
Good luck with the tutorial! I went there too, though without this library it really was a mess. Didn't actually have the courage to try to finish the tutorial before working on this. Don't hesitate if you find more limitations/bugs, AFAIK there haven't been extensive uses yet, so you are likely to encounter some corner cases :)

Also feel free to look at [this comment](https://github.com/JuliaGPU/Vulkan.jl/issues/7#issuecomment-820542876) for some WIP if that may help.
