### ISSUE TITLE
`VkPresentModeKHR` has no high level equivalent `PresentModeKHR`

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#17]
I think this enum would have to be added in VulkanCore and this package would need a new set of generated functions, as the wrapper for `get_physical_device_surface_present_modes_khr` right now returns `::Vektor{VkPresentModeKHR}` instead of the documented `::Vektor{PresentModeKHR}`. Not sure how those all get generated though.

I'd be happy to add the necessary code though, provided I can find out where it is.

**Comment by Seelengrab** [comment]
Hmm, no, it does seem to exist in VulkanCore.jl

[Definition](https://github.com/JuliaGPU/VulkanCore.jl/blob/3134e6ba7e56de92d81b70a7167cf6328557b6d6/gen/vk_common.jl#L5510-L5518)

**Comment by Seelengrab** [comment]
Ah, this is 0.1.3, not sure if this is fixed on master already

**Comment by serenity4** [comment]
Ah, yes it's a bug in the documentation rather than in the wrapper. It extends not only to `VkPresentModeKHR` but also to all enums that are not bitmasks, and appears for the documentation of vectors of enums. The thing is, we do not have any wrapper around such enums, because they would be identical to the VulkanCore counterpart.

The one thing we could do is add aliases everywhere `const PRESENT_MODE_... = VK_PRESENT_MODE_...`, though for now I haven't found it of interest.

**Comment by Seelengrab** [comment]
I see - if it's just a doc issue, I'll just continue with the tutorial. I'll leave this issue open so we don't forget about the docs or the constant, whichever route is preferred.

**Comment by serenity4** [comment]
Yes, it should work fine since we don't type vectors in signatures (so that we can pass in `Any[]` vectors).

**Comment by Seelengrab** [comment]
Are there other places where the versions with prefix `Vk` are to be used? I'd define the constants without the prefix, purely to make it clear that those are to be used from this "high level" view.

**Comment by serenity4** [comment]
It's only for non-bitmask enums (instances, with the prefix `VK_` but also their type with `Vk`). I admit that having to type in the prefix here and not for all other variables is a bit confusing, and we may gain to make a clear separation between VulkanCore variables and wrapped variables.

**Comment by Seelengrab** [comment]
After trying to run the code, turns out, it's not only a doc issue - because of the type assert in `get_physical_device_surface_present_modes_khr`, it throws an `UndefVarError`, as `PresentModeKHR` is not defined 😅

**Comment by serenity4** [comment]
Ah. I'll fix that right away.

**Comment by serenity4** [comment]
It now generates the correct result types (there were two other functions affected) with the prefix `Vk`. There remains the issue of having to type in the prefix for enum types, so we can leave this one open.

**Comment by Seelengrab** [comment]
Yep, works now!

**Comment by serenity4** [comment]
In the new version all `VK_*` types and constants were removed and wrappers for enum types and constants were generated. So now you have

```julia
julia> using Vulkan

julia> PresentModeKHR
Cenum PresentModeKHR:
PRESENT_MODE_IMMEDIATE_KHR = 0x00000000
PRESENT_MODE_MAILBOX_KHR = 0x00000001
PRESENT_MODE_FIFO_KHR = 0x00000002
PRESENT_MODE_FIFO_RELAXED_KHR = 0x00000003
PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR = 0x3b9c7b98
PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR = 0x3b9c7b99
```

This way it should be much more consistent, and `vk`/`Vk`/`VK_` prefixes are normally not used anywhere in the wrapper.
