### ISSUE TITLE
`SwapchainKHR` directly passes its arguments to `create_swapchain_khr`

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#19]
`SwapchainKHR` directly passes its arguments to `create_swapchain_khr`, which expects a `SwapchainCreateInfoKHR` instead of the individual arguments. Is this supposed to be this way and should I create the info struct in this case?

**Comment by Seelengrab** [comment]
After investigating, I think it should create the `SwapChainCreateInfoKHR` inside of the generated wrapper, not sure why it's not being generated properly 🤔

So either [this](https://github.com/JuliaGPU/Vulkan.jl/blob/57d1b86ed0f27f6cf517bef1ab314fc4c5ad93ba/generated/vulkan_wrapper.jl#L5171)  or [this](https://github.com/JuliaGPU/Vulkan.jl/blob/57d1b86ed0f27f6cf517bef1ab314fc4c5ad93ba/generated/vulkan_wrapper.jl#L7002) should map to `unwrap(create_swapchain_khr(device, SwapchainCreateInfoKHR(...), old_swapchain))` instead, I think.

**Comment by serenity4** [comment]
It's definitely a bug :sweat: thanks for reporting all these bugs.
Just spotted another bug with `create_shared_swapchains_khr`. I'll fix these as soon as possible.

**Comment by Seelengrab** [comment]
You're welcome! I guess once I'm fully done with vulkan-tutorial.com, this wrapper will be perfect to use for all kinds of projects 😁

**Comment by Seelengrab** [comment]
By the way, I'll be saving the code that I wrote while going through the tutorial and will push it to github some time in the future, with tags corresponding to each chapter of the tutorial. May be useful to someone.

**Comment by serenity4** [comment]
That would be great. It would be a fantastic (indirect) test suite for this package.

**Comment by serenity4** [comment]
Fixed by 61de2405718874b7a4ff14673e3e00cf18ab78d9. The missing bit was actually just a method for `create_swapchain_khr` which calls `create_swapchain_khr` but with the assembled create info structure.
