### ISSUE TITLE
Not an issue, can be closed soon(ish)

### ISSUE THREAD

**Issue by Seelengrab** [JuliaGPU/Vulkan.jl#22]
I'm proud to announce - we've got a triangle!

![image](https://user-images.githubusercontent.com/11753998/117536893-fe1f8f80-affd-11eb-91e7-e34e8e12196e.png)

Over all, this was really not as bad as I thought it would be :D

**Comment by serenity4** [comment]
Congratulations! That was quick.

I just created [a stream](https://julialang.zulipchat.com/#narrow/stream/287693-vulkan) in Zulip, don't hesitate to post things there! :smile:

**Comment by Seelengrab** [comment]
It was mostly just finding the time to continue with the tutorial ^^
