### ISSUE TITLE
Convenience Constructor for PhysicalDeviceVulkan12Features

### ISSUE THREAD

**Issue by maj0e** [JuliaGPU/Vulkan.jl#25]
Hi,

it would be nice to have constructors from a list of symbols for  `PhysicalDeviceVulkan11Features` and `PhysicalDeviceVulkan12Features`, equivalently to the constructor you wrote for `PhysicalDeviceFeatures`.
I took your existing code and adapted it slightly  for the other two structs:

In `src/device.jl`
``` julia
function PhysicalDeviceVulkan11Features(features::AbstractArray; next = C_NULL)
    names = filter(n -> n ∉ (:sType, :pNext), fieldnames(VkPhysicalDeviceVulkan11Features))
    diff = setdiff(collect(features), names)
    if length(diff) > 0
        error("Invalid physical device Vulkan 1.1 features: $(join(diff, ", "))")
    end
    args = map(in(features), names)
    PhysicalDeviceVulkan11Features(args...; next=next)
end

PhysicalDeviceVulkan11Features(features::Symbol...) = PhysicalDeviceVulkan11Features(collect(features))

function PhysicalDeviceVulkan12Features(features::AbstractArray; next = C_NULL)
    names = filter(n -> n ∉ (:sType, :pNext), fieldnames(VkPhysicalDeviceVulkan12Features))
    diff = setdiff(collect(features), names)
    if length(diff) > 0
        error("Invalid physical device Vulkan 1.2 features: $(join(diff, ", "))")
    end
    args = map(in(features), names)
    PhysicalDeviceVulkan12Features(args...; next=next)
end

PhysicalDeviceVulkan12Features(features::Symbol...) = PhysicalDeviceVulkan12Features(collect(features))
```

Note that I had to add a filter to exclude `sType`and `pNext` to get the correct argument list. 
Beside that, these functions are mostly identical, so you may find it cleaner to generate them somehow with a macro.

Thanks for the great package btw

**Comment by serenity4** [comment]
Thank you for suggesting these improvements! They are definitely welcome. I'll tag a new release with these changes.
