### ISSUE TITLE
Unsatisfiable requirements detected for package Vulkan

### ISSUE THREAD

**Issue by jeannekamikaze** [JuliaGPU/Vulkan.jl#29]
Hello. I am running into the following error installing the `Vulkan` package on a clean Julia install. The `VulkanCore` package, on the other hand, installs just fine. I am not sure what specifically is causing the version restriction. Could somebody help?

Thank you.

```
ERROR: Unsatisfiable requirements detected for package Vulkan [9f14b124]:
 Vulkan [9f14b124] log:
 ├─possible versions are: [0.1.0-0.1.3, 0.2.0-0.2.4, 0.3.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0-0.1.3, 0.2.0-0.2.4, 0.3.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by serenity4** [comment]
Hi, it looks like a Julia version compatibility issue. Note that this package only supports Julia 1.5 and above. What version are you using?

**Comment by jeannekamikaze** [comment]
Thank you, that was indeed the issue. I was on `1.0.3`, upgrading to `1.6.2` worked. The issue was not exactly obvious from the error above.
