### ISSUE TITLE
fails to find vulkan validation layer on 1.8 (linux)

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaGPU/Vulkan.jl#38]
Previously when I had used this package in Julia 1.7 it seemed to be able to find the lib for the validation layer that was installed on my system.

On 1.8 it seems to be failing to link to it:
```julia
ERROR: ERROR_LAYER_NOT_PRESENT: failed to execute #= /home/expandingman/.julia/packages/Vulkan/bHXH3/generated/linux.jl:46990 =# @dispatch nothing vkCreateInstance(create_info, allocator, pInstance)
Stacktrace:
 [1] unwrap(r::ResultTypes.Result{Instance, VulkanError})
   @ ResultTypes ~/.julia/packages/ResultTypes/AUZ9z/src/ResultTypes.jl:67
 [2] Instance(enabled_layer_names::Vector{String}, enabled_extension_names::Vector{String}; allocator::Ptr{Nothing}, next::Ptr{Nothing}, flags::Int64, application_info::ApplicationInfo)
   @ Vulkan ~/.julia/packages/Vulkan/bHXH3/generated/linux.jl:66011
```

I have confirmed that `/lib/libVkLayer_khronos_validation.so` exists.

I tried figuring out where in the code it tries to link to them to determine why it's failing but so far I haven't found it.

**Comment by serenity4** [comment]
Could it be that the validation layer fails to load as described [here](https://juliagpu.github.io/Vulkan.jl/dev/troubleshooting/#ERROR_LAYER_NOT_PRESENT)? I had some issues with GLIBCXX not found with recent updates to validation layers.

**Comment by ExpandingMan** [comment]
Maybe?  I can't figure out how to debug this though, I have a debug messenger (I think, though I guess this error is happening before it gets created).

Can you point to where in the code it is trying to find the lib?  I haven't been able to find it and I am quite confused about how it's looking for it in the first place.

**Comment by serenity4** [comment]
> Can you point to where in the code it is trying to find the lib? I haven't been able to find it and I am quite confused about how it's looking for it in the first place.

The loading does not happen within the library; it is the [Vulkan loader](https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderInterfaceArchitecture.md) which does that. It happens in the `vkCreateInstance` C function.

> I have a debug messenger (I think, though I guess this error is happening before it gets created).

Yes it is, hence the part

> simply pass in a [DebugUtilsMessengerCreateInfoEXT](https://juliagpu.github.io/Vulkan.jl/dev/api/#Vulkan.DebugUtilsMessengerCreateInfoEXT) as a next member of your [InstanceCreateInfo](https://juliagpu.github.io/Vulkan.jl/dev/api/#Vulkan.InstanceCreateInfo)

which allows the Vulkan loader to report debug info even though it happens before creating the debug messenger. It should report (if you have all logging levels enabled) where it looks for layers, and reports on loading them, including any errors.
You should be able to see an `@error` printing out whatever error you're getting if you are using the [debug messenger callback](https://juliagpu.github.io/Vulkan.jl/dev/api/#Vulkan.default_debug_callback-NTuple{4,%20Any}) from Vulkan.jl (as a C function, see the note about `callback` from [this documentation](https://juliagpu.github.io/Vulkan.jl/dev/api/#Vulkan.DebugUtilsMessengerEXT-Tuple{Instance,%20Ptr{Nothing}})).

**Comment by ExpandingMan** [comment]
Wow, I am a gigantic idiot:

> Note that any layer that fails to load is simply ignored, and may be reported as not present (in particular this can be triggered by ['GLIBCXX_X.X.XX' not found](https://juliagpu.github.io/Vulkan.jl/dev/troubleshooting/#libstdc)).

Somehow the idea that having an incompatible glibcxx seemed so non sequitur to me that even though it said this in the troubleshooting I just could not seem to get it through my head.

So, I opened this in error, the documentation already addresses it.  Kind of scary that vulkan has this elaborate loading mechanism rather than just linking libs like a normal person, it makes these issues very confusing, though I imagine there is probably a reason for it (performance somehow?).
